//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nedeljni_I_Dejan_Prodanovic.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProject
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblProject()
        {
            this.tblDailyReports = new HashSet<tblDailyReport>();
        }
    
        public string ProjectName { get; set; }
        public string ClientName { get; set; }
        public string ProjectDescription { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> AgreedFinishingDate { get; set; }
        public Nullable<decimal> HourPayment { get; set; }
        public string Realization { get; set; }
        public Nullable<int> ContractManagerID { get; set; }
        public Nullable<int> ProjectLeaderID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblDailyReport> tblDailyReports { get; set; }
        public virtual tblManager tblManager { get; set; }
        public virtual tblManager tblManager1 { get; set; }
    }
}
