//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nedeljni_I_Dejan_Prodanovic.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwEmployee2
    {
        public string YearsOfService { get; set; }
        public Nullable<decimal> Salary { get; set; }
        public Nullable<int> ManagerID { get; set; }
        public string ProfessionalQualifications { get; set; }
        public Nullable<bool> IsNewRequest { get; set; }
        public Nullable<int> PositionID { get; set; }
        public Nullable<int> SectorID { get; set; }
        public int EmployeeID { get; set; }
        public int UserID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Gender { get; set; }
        public string JMBG { get; set; }
        public string Residence { get; set; }
        public string MaritalStatus { get; set; }
        public string Username { get; set; }
    }
}
