//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nedeljni_I_Dejan_Prodanovic.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwManager
    {
        public Nullable<int> NumberOfSuccesfullProjects { get; set; }
        public string OfficeNumber { get; set; }
        public int ManagerID { get; set; }
        public string Email { get; set; }
        public string ResponsibilityLevel { get; set; }
        public int UserID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Gender { get; set; }
        public string JMBG { get; set; }
        public string Residence { get; set; }
        public string MaritalStatus { get; set; }
        public string Username { get; set; }
    }
}
